import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import { useMoralis } from "react-moralis";
import { NFT } from 'web3uikit';


const supportedChains = ["31337", "4"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Resistanc3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      
      

      <div className={styles.title}>
          <h1>We are a DAO Community</h1>
          <div className={styles.pointer}></div>
          <img src="https://github.com/itsjenm/resistanc3/blob/main/img/resistanc3_High_Res_Logo.png?raw=true" className="logo" style={{ width: "40%", height: "auto"}}></img>
          

          <div className={styles.pointer2}>
          </div>

      </div>

    
      {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(parseInt(chainId).toString()) ? (
            <div className="flex flex-row">
              <LotteryEntrance className="p-8" />
            </div>
          ) : (
            <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
          )}
        </div>
      ) : (
        <div>Please connect to a Wallet</div>
      )}
      <div className={styles.main}>
      <h3>How it works\\</h3>
      <p>
      <NFT address="0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB"
  chain="eth"
  fetchMetadata
  metadata={{}}
  name="punk-nft"
  tokenId="1" />
      </p>
      </div>
    </div>
  );

}
